split_targets: Allow to run unstable test
ansible/ansible-zuul-jobs pull request #1203
Opened 2021-11-02 08:50 UTC by Akasurde

When targets are specified explicitly, run targets
even if they are marked as unstable.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

2021-11-02 08:50 UTC, Akasurde commented
cc @goneri

2021-11-15 17:15 UTC, goneri requested changes

2021-11-15 17:15 UTC, goneri commented on roles/ansible-test-splitter/files/split_targets.py
> +        if to_skip_because_disabled(lines) and not targets_from_cli:
You also include disabled target. Is this something expected? The PR title just mentions the unstable targets.

2021-11-15 17:15 UTC, goneri commented on roles/ansible-test-splitter/files/test_split_targets.py
> +        ({"test1": ["cloud/aws"]}, "", ([], ["test1"])),
`targets_from_cli` is a list but you pass a string.

2021-11-15 17:15 UTC, goneri commented on roles/ansible-test-splitter/files/split_targets.py
> +        if to_skip_because_disabled(lines) and not targets_from_cli:
Also, if `targets_from_cli` is empty, we should ignore the filter. I think we should instead have something like:

`if to_skip_because_unstable(lines) and target_name not in targets_from_cli:`

2021-11-17 17:11 UTC, goneri approved these changes

2021-11-17 17:16 UTC, Akasurde commented
@goneri Thanks for the review and merge.

2021-11-17 17:22 UTC, goneri commented
> @goneri Thanks for the review and merge.

You're welcome. Thank you for the adjustments.

2021-11-17 17:23 UTC, merged