To fix TM deepsec py27, 35 and 36 jobs
ansible/ansible-zuul-jobs pull request #1224
Opened 2021-11-17 07:11 UTC by justjais

To fix TM deepsec py27, 35 and 36 jobs

2021-11-17 15:15 UTC, goneri commented
recheck

2021-11-29 15:51 UTC, goneri requested changes

2021-11-29 15:51 UTC, goneri commented on zuul.d/nodesets.yaml
> +      - name: appliance
Please reuse the group organisation of `Trendmicro-DeepSecurity-20.0.344-python38`. You should have `appliance-ssh` and `aws` groups.

2021-11-30 13:46 UTC, GomathiselviS commented
recheck

2021-11-30 14:02 UTC, GomathiselviS approved these changes

2021-11-30 14:06 UTC, goneri approved these changes

2021-11-30 14:17 UTC, merged