added ansible-test jobs for ovs
ansible/ansible-zuul-jobs pull request #1521
Opened 2022-05-04 12:14 UTC by komaldesai13

added ansible-test and removed ansible-ee for OVS

2022-05-06 08:57 UTC, trishnaguha commented on zuul.d/project-templates.yaml
>          - build-ansible-collection:
stable-2.13 test job is required

2022-05-06 13:09 UTC, goneri commented on zuul.d/openvswitch-openvswitch-jobs.yaml
> +    run: playbooks/ansible-network-openvswitch-appliance/run.yaml
This run.yaml is actually empty.
You should instead run `playbooks/ansible-test-base/run.yaml`

2022-05-06 13:11 UTC, goneri requested changes

2022-05-06 13:11 UTC, goneri commented on zuul.d/openvswitch-openvswitch-jobs.yaml
> +    run: playbooks/ansible-network-openvswitch-appliance/run.yaml
You can also add: `post-run: playbooks/ansible-test-base/post.yaml`

2022-05-06 13:11 UTC, goneri commented on zuul.d/openvswitch-openvswitch-jobs.yaml
> +    run: playbooks/ansible-network-openvswitch-appliance/run.yaml
You can use ansible-test-cloud-integration-vcenter as an example.

2022-05-13 09:45 UTC, komaldesai13 commented
recheck

2023-08-16 10:07 UTC, closed without merging